//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "姓名")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "帳號")]
        [EmailAddress]
        [Required]
        public string Email { get; set; }

        [Display(Name = "密碼")]
        [Required]
        public string Pwd { get; set; }

        [Display(Name = "電話")]
        [Required]
        public string Phone { get; set; }
    }
}
