//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetails
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "訂單編號")]
        public string OrderId { get; set; }

        [Display(Name = "會員編號")]
        public Nullable<int> MemberId { get; set; }

        [Display(Name = "產品編號")]
        public string PId { get; set; }

        [Display(Name = "產品名稱")]
        public string PName { get; set; }

        [Display(Name = "單價")]
        public Nullable<int> PPrice { get; set; }

        [Display(Name = "數量")]
        public Nullable<int> Qty { get; set; }

        [Display(Name = "圖片")]
        public string Image { get; set; }

        [Display(Name = "是否為訂單")]
        public Nullable<int> IsApproved { get; set; }
    }
}
