//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "訂單編號")]
        public string OrderId { get; set; }

        [Display(Name = "會員編號")]
        public int MemberId { get; set; }

        [Display(Name = "收件人姓名")]
        public string Receiver { get; set; }

        [Display(Name = "收件人信箱")]
        public string ReceiverEmail { get; set; }

        [Display(Name = "收件人地址")]
        public string RecevierAddr { get; set; }

        [Display(Name = "訂單日期")]
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
