//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Demo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tCustomer
    {
        [Key]
        public int fId { get; set; }

        [Required(ErrorMessage ="***姓名為必填欄位***")]
        [Display(Name ="姓名")]
        public string fName { get; set; }

        [Required(ErrorMessage = "***電話為必填欄位***")]
        [Display(Name = "電話")]
        public string fPhone { get; set; }

        [Required(ErrorMessage = "***Email為必填欄位***")]
        [Display(Name = "Email")]
        public string fEmail { get; set; }


        [Display(Name = "地址")]
        public string fAddress { get; set; }
    }
}
