//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadImg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tb_image
    {
        [Key]
        public int ImageId { get; set; }

        [Display(Name ="名稱")]
        [Required(ErrorMessage = "***名稱是必填欄位***")]
        public string Title { get; set; }

        [Display(Name ="圖檔")]
        public string ImagePath { get; set; }

        //[Required(ErrorMessage = "***請選擇檔案***")]
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
